In [94]:
import pandas as pd
import numpy as np
import explain_trees as et
import pickle

In [161]:
from imp import reload
reload(et)

<module 'explain_trees' from '/Users/sandyryza/explain-trees/explain_trees.py'>

In [134]:
from sklearn.datasets import load_iris
from sklearn.ensemble import GradientBoostingClassifier
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
labels = pd.Series(np.random.rand(len(df.index)) < 0.5)
model = GradientBoostingClassifier(n_estimators=10, max_depth=3).fit(df, labels)

In [135]:
from sklearn.tree import DecisionTreeClassifier
model = DecisionTreeClassifier().fit(df, iris.target)

In [98]:
model = pickle.load(open('/Users/sandyryza/data_science/dt_model.pkl', 'rb'))

In [146]:
model.tree_.children_left

array([ 1, -1,  3,  4,  5, -1, -1,  8, -1, 10, -1, -1, 13, 14, -1, -1, -1])

In [147]:
model.tree_.children_right

array([ 2, -1, 12,  7,  6, -1, -1,  9, -1, 11, -1, -1, 16, 15, -1, -1, -1])

In [148]:
model.tree_.feature

array([ 2, -2,  3,  2,  3, -2, -2,  3, -2,  0, -2, -2,  2,  0, -2, -2, -2])

In [149]:
et.explain_tree_prediction(model, df.iloc[0])

[(2, 50.0, 1.3999999999999999, True, 0.66666666666666674)]

In [162]:
example = df.iloc[4]
et.prediction_descriptions(model, example)

['petal length (cm)=1.400000 <= 3.600000']

In [123]:
model.predict(df.iloc[0])

/Users/sandyryza/.pyenv/versions/3.4.3/lib/python3.4/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([0])

In [100]:
x = model.estimators_[0][0].tree_.impurity

AttributeError: 'DecisionTreeClassifier' object has no attribute 'estimators_'

In [166]:
model.tree_.threshold

array([ 2.45000005, -2.        ,  1.75      ,  4.94999981,  1.6500001 ,
       -2.        , -2.        ,  1.54999995, -2.        ,  6.94999981,
       -2.        , -2.        ,  4.85000038,  5.94999981, -2.        ,
       -2.        , -2.        ])

In [163]:
dir(model.tree_)

['__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__pyx_vtable__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'apply',
 'capacity',
 'children_left',
 'children_right',
 'compute_feature_importances',
 'feature',
 'impurity',
 'max_depth',
 'max_n_classes',
 'n_classes',
 'n_features',
 'n_node_samples',
 'n_outputs',
 'node_count',
 'predict',
 'threshold',
 'value',
 'weighted_n_node_samples']

array([ True, False, False, False,  True, False, False,  True, False,
       False,  True,  True, False,  True, False, False, False,  True,
       False,  True, False,  True, False, False, False, False, False,
       False, False,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True, False, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False, False,  True, False,
        True, False, False,  True, False, False,  True,  True, False,
       False,  True,  True, False,  True, False,  True, False, False,
        True,  True,  True, False, False,  True,  True, False,  True,
        True, False,  True, False, False,  True, False,  True,  True,
        True,  True, False,  True, False,  True, False, False, False,
        True,  True, False, False,  True, False, False, False,  True,
       False, False, False, False,  True,  True, False, False,  True,
        True, False,  True, False,  True,  True, False, False, False,
       False, False,

In [68]:
labels.iloc[0]

False